name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Specify the PHP version you want to use

    # Step 3: Install dependencies using Composer
    - name: Install dependencies
      run: |
        composer install

    # Step 4: Run PHPUnit tests
    - name: Run PHPUnit tests
      run: |
        ./vendor/bin/phpunit --configuration phpunit.xml

    # Optional Step: Post test results or custom message (if desired)
    - name: Post test results (optional)
      if: always()
      run: |
        echo "Tests completed"

